### ISSUE TITLE
blob panic

### ISSUE THREAD

**Issue by coocood** [coocood/badger#146]
panic: runtime error: slice bounds out of range [:829389531] with capacity 50538476

goroutine 99 [running]:
github.com/coocood/badger.(*blobGCHandler).extractValidEntries(0xc00ab02e80, 0x0, 0x0, 0x0, 0xc0131de070, 0xc078ade000, 0x30325ec, 0x30327ec, 0x18aaa, 0xc03b9c19e0, ...)
	/Users/zhou/gopath/pkg/mod/github.com/coocood/badger@v1.5.1-0.20191031155124-64a2ad772588/blob.go:691 +0x4ae
github.com/coocood/badger.(*blobGCHandler).doGCIfNeeded(0xc00ab02e80, 0xc023d03980, 0x1)
	/Users/zhou/gopath/pkg/mod/github.com/coocood/badger@v1.5.1-0.20191031155124-64a2ad772588/blob.go:571 +0x27f
github.com/coocood/badger.(*blobGCHandler).run(0xc00ab02e80)
	/Users/zhou/gopath/pkg/mod/github.com/coocood/badger@v1.5.1-0.20191031155124-64a2ad772588/blob.go:472 +0x8c
created by github.com/coocood/badger.(*blobManager).Open
	/Users/zhou/gopath/pkg/mod/github.com/coocood/badger@v1.5.1-0.20191031155124-64a2ad772588/blob.go:297 +0x58a

**Comment by coocood** [comment]
panic: runtime error: slice bounds out of range [3459219564:40155031]

goroutine 58 [running]:
github.com/coocood/badger.(*blobGCHandler).buildDiscardPhysicalOffsets(0xc000096000, 0xc01db364e0, 0xc03b80c000, 0x270ecb7, 0x270eeb7, 0x4d7b5a0, 0xc003a3c240)
	/Users/zhou/gorepo/src/github.com/coocood/badger/blob.go:704 +0x207
github.com/coocood/badger.(*blobGCHandler).extractValidEntries(0xc000096000, 0x0, 0x0, 0x0, 0xc01db364e0, 0xc03b80c000, 0x270ecb7, 0x270eeb7, 0x11387, 0x13aaa, ...)
	/Users/zhou/gorepo/src/github.com/coocood/badger/blob.go:670 +0x185
github.com/coocood/badger.(*blobGCHandler).doGCIfNeeded(0xc000096000, 0x0, 0x0)
	/Users/zhou/gorepo/src/github.com/coocood/badger/blob.go:568 +0x2f6
github.com/coocood/badger.(*blobGCHandler).run(0xc000096000)
	/Users/zhou/gorepo/src/github.com/coocood/badger/blob.go:468 +0x8c
created by github.com/coocood/badger.(*blobManager).Open
	/Users/zhou/gorepo/src/github.com/coocood/badger/blob.go:292 +0x58a
